local PrescriptCode = "4FlrNeMqpEr"
if PrescriptCode ~= loadstring(game:HttpGet("https://raw.githubusercontent.com/aethveil/the-prescript-s-will/refs/heads/main/code.lua", true))() then return false end
return {
 "Parry every attack you see from another fixer until your hands bleed out through your gloves, then offer the bloodied palms to the nearest Backstreets gutter rat as tribute.",
 "Enter the Night in the Backstreets. Allow the first three pd gankers to strike you without parrying or blocking, then flee while screaming your own name backward repeatedly until you either die or escape. If you can't chat, spin 360 while running instead.",
 "Craft a weapon using only parts harvested from dead freshies. Use it to execute a perfect parry chain on five consecutive PvP opponents, then jump off a building while in combat. If you didn't die, go to a permadeath server and find the first ranked person and call them trash and hit them twice before running. If you had a Book of Library and it dropped, you cannot do anything else until you get a book of library just from begging.",
 "Recruit a member to The Index. Show them a video or screenshot of you getting this prescript as proof.",
  "Recruit a member to The Index. Show them a video or screenshot of you getting this prescript as proof.",
   "Recruit a member to The Index. Show them a video or screenshot of you getting this prescript as proof.",
    "Recruit a member to The Index. Show them a video or screenshot of you getting this prescript as proof.",
 "Approach a cooking station in the open streets. Consume raw ingredients until your stomach ruptures visibly. Do not heal. Continue gripping passersby with your exposed entrails hanging until the rupture stops bleeding.",
 "Seek out the highest grade member you can find in the streets. Kneel before them, remove your own tongue with whatever blade you carry, and present it while staring directly into their eyes without blinking.Complete within this day.",
 "Carry a knocked Grade 1 Zwei fixer to Hana Outpost, present them to the Manager by shattering your weapon on your own spine first.",
 "Manifest E.G.O at Sentenza then parry every Office Contractor quest offer until your blade snaps against their desk.",
 "Enter the Death Sentence arena during Night. Survive five full waves using only parries executed with your bare fists. Allow the sixth wave to rupture your torso completely before retreating.",
 "Approach the Hana Association outpost. Kneel at the entrance and consume one full stack of raw meat until your jaw dislocates. Do not heal the dislocation. Remain kneeling until a fixer attempts to speak to you, then spit the undigested meat directly into their face.",
 "Join Sentenza during peak Night hours. Consume three stacks of raw Enkephalin from the bar counter until your veins rupture, then offer the spilling blood to the first Twinhook Pirate who approaches.",
 "Survive eight full waves of Death Sentence using only bare fist parries on every attack. On completion, drive your knuckles through your own eye sockets and scream your Syndicate name into the void.",
 "Approach five different fixers in the Backstreets and ask each one, in a completely flat voice, to rate the smell of your armpit on a scale of one to ten. Do not react to their answers. Walk away immediately after the tenth rating",
 "During Night in the Backstreets, walk backward for exactly three hundred steps while reciting the value of E. If you trip or turn around, start the count over from zero.",
 "Buy one cheap coffee from the nearest vending machine. Carry it untouched to Hana Outpost. Once there, pour the entire cup slowly over your own shoes while maintaining perfect eye contact with the nearest Association clerk. Do not explain.",
 "Grip no one today. Instead, whenever you see another Index member, bow deeply at a ninety-degree angle and remain bowed until they have walked at least ten paces past you. Repeat for every Index member encountered.",
 "Stand in the middle of the busiest Backstreets intersection for thirty minutes while slowly spinning clockwise. If anyone bumps into you, apologize by saying 'The City forgives' in the flattest voice possible.",
 "Go to Everything Workshop and ask the Workshop Master to 'upgrade' your weapon by hitting it with a normal hammer exactly 47 times. Thank them after each hit. Leave without testing it.",
 "Sit on the ground outside Sentenza bar and count aloud every person who walks past you until you reach 100. If you lose count, start over while clapping once for every restart.",
 "Manifest your E.G.O suit, then unequip it piece by piece in front of a vending machine. Place each piece into the vending machine slot as if paying for something that doesn't exist.",
 "Follow the nearest non-Index player for exactly 200 steps without speaking or attacking. If they turn around and look at you, freeze completely until they walk away or attack.",
 "Enter Death Sentence but leave after wave 1. Repeat this exact sequence five times in a row without doing anything else in between.",
 "Buy the cheapest food item available, carry it to the Hana Outpost entrance, place it on the ground, then kneel and stare at it for ten full minutes without touching it.",
 "Whenever you see another Index Proselyte today, approach them silently and mime eating an invisible sandwich very slowly until they leave or react.",
 "Walk to the nearest event spawn zone during day, stand directly in front of it without fighting, and wave politely every time it moves. Do this until it disappears or attacks you.",
 "Go to the cooking station and cook the most expensive recipe you can afford, then throw the finished dish directly into the nearest trash pile without eating any of it.",
 "Stand perfectly still next to a gripped corpse for fifteen minutes. If anyone asks what you're doing, respond only with 'Waiting for the Prescript to finish' and resume silence.",
 "Ask ten random players in the Backstreets what their favorite abnormality is. After each answer, nod once, then immediately walk ten steps backward without turning around.",
 "Equip your worst possible weapon, go to Sentenza, and challenge the first person you see to a duel while loudly announcing that you will only parry with your off-hand.",
 "Travel from one end of the Backstreets to the other while only moving by rolling forward. If you get stuck or attacked, you must roll in place for thirty seconds before continuing.",
 "Stand under the tallest streetlight in the Backstreets for exactly twenty minutes. Do not move or speak. If anyone approaches, tilt your head and stare directly at their shoes until they leave.",
 "Walk backward from Hana Outpost to Sentenza while whispering your own Syndicate name. Restart the path if you step off the intended route or trip over an obstacle.",
 "Parry every attack you see for exactly three minutes using only your off-hand weapon. Afterward, kneel and trace invisible symbols in the air for an additional five minutes without stopping.",
 "Approach the nearest Index member and bow deeply, then recite the numbers from 1 to 100 in a monotone voice without blinking. Remain in place until they leave or interact first.",
 "Walk in a perfect circle around any corpse you encounter in the Backstreets. Complete exactly seven rotations before stepping away silently.",
 "Stand on the edge of the nearest platform or rooftop and count aloud every visible NPC for ten minutes. If you lose count, begin again and do not blink until complete.",
 "Follow a random non-Index player for exactly fifty steps without attacking. If they notice you, freeze immediately and remain motionless until they continue walking.",
 "Kneel at the entrance of Sentenza bar and hum a continuous note for five minutes. If anyone bumps into you, restart the hum sequence without acknowledgment.",
 "Manifest your E.G.O suit, remove it entirely piece by piece in full view of at least two players, and place each piece on the ground while staring straight ahead. Do not speak.",
 "During Night, spin in place at the busiest Backstreets intersection exactly one hundred times. If anyone touches you, apologize by saying 'The City watches' before resuming.",
 "Walk backward while counting steps aloud and reciting the first ten digits of Pi. Reset count each time you stop moving or turn around.",
 "Approach the nearest player silently, kneel, and wave both hands in small arcs while remaining silent until they leave the area.",
 "Stand still in the middle of Death Sentence arena without attacking for one full wave. If attacked, parry once, then resume immobility until the wave ends.",
 "Walk across the Backstreets while waving politely at every NPC you pass. Restart the walk if you miss an NPC or fail to maintain a consistent wave.",
 "Kneel at the nearest vending machine and whisper your rank to it repeatedly for five minutes. Stand only when a new player walks past without noticing you.",
 "Parry every visible attack for exactly two minutes, then sit cross-legged in place without moving for an additional minute while keeping perfect focus on the nearest NPC.",
 "Walk exactly 100 steps forward while holding a neutral stance, then spin 180 degrees and repeat in the opposite direction. Resume until you complete the circuit twice.",
 "Approach five different Index members and ask them a simple question with a completely flat voice. Immediately walk backward ten paces after each answer without responding further.",
 "During Night, walk toward the tallest building while counting aloud in a monotone voice. If interrupted by another player, restart the sequence from your original position.",
 "Stand silently at the entrance of the nearest arena and nod once toward every player who passes. Reset your stance if anyone stops to interact with you.",
 "Manifest your E.G.O suit at Sentenza, then kneel silently while observing all players for exactly ten minutes without moving or speaking.",
 "Walk from Hana Outpost to the edge of the Backstreets without turning your head. If you see another player, continue moving forward and count them aloud silently in your head until you reach the destination.",
 "Follow the nearest Index member silently, maintaining exact distance for exactly seventy steps, then kneel without speaking.",
"Kneel and whisper a number sequence aloud corresponding to the number of visible lights in the area. Do not pause until completed.",
"Walk only along the shadows in the Backstreets, avoiding lighted areas entirely. Restart if you step into a shadow incorrectly.",
"Stand on a stairwell and alternate stepping up and down precisely thirty times while staring at the nearest wall. Repeat if anyone watches.",
"Spin clockwise exactly three times at the center of a Dead Streets intersection, then walk backward five paces without turning.",
"Manifest your E.G.O suit, remove the chest piece last, then kneel silently while counting invisible footsteps for seven minutes.",
"Walk backward toward Sentenza while raising your weapon above your head. Lower it only when reaching the other side.",
"Recite a random sequence of numbers aloud for exactly five minutes. Pause only if someone speaks to you; resume silently afterward.",
"Stand near the edge of a platform and mimic the posture of the first NPC you see. Maintain until they move away or you are attacked.",
"Parry the first three attacks from every fixer in Sentenza using your weakest weapon, then drop the weapon silently and walk away.",
"Kneel at the center of a street and spin once per minute while counting aloud in reverse the letters of the first player you saw today.",
"Walk diagonally across the Backstreets while shouting only the word 'Observe' each time you step forward. Restart if interrupted.",
"Manifest your E.G.O suit at night, then slowly remove each piece in random order while standing still for exactly ten minutes.",
"Follow a random NPC silently for fifty steps while reciting their movement in your head in reverse order. Pause if noticed.",
"Sit cross-legged in the middle of the busiest intersection and hum continuously until nightfall without moving or speaking.",
"Kneel near the Hana Outpost entrance and repeat silently the first three words of the last Prescript you completed.",
"Walk from Sentenza to Death Sentence arena while counting aloud each shadow you step over. Restart if a shadow is missed.",
"Parry every attack visible in a ten-step radius for exactly three minutes. Kneel afterward and hold your hands out flat for double the time.",
"Stand at the edge of a rooftop and perform a perfect spin without moving your feet. Repeat seven times before stepping back safely.",
"Walk only in small hops through the Backstreets for one hundred steps. Pause for exactly ten seconds if anyone notices.",
"Manifest your E.G.O suit, remove your gloves first, then stand silently while staring at every NPC for five minutes.",
"Follow the nearest Index member exactly two paces behind them without moving closer or further. Continue until they leave the area.",
"Kneel at Sentenza bar and mime drinking from an invisible cup for exactly seven minutes. Do not react to anyone walking by.",
"Walk backward while spinning clockwise at every corner. Reset if you step outside the pattern or collide with another player.",
"Stand on a stairwell and count aloud to seventy-two while performing invisible parries for each number. Repeat if interrupted.",
"Sit in the middle of the Backstreets and pretend to juggle three invisible objects for exactly five minutes without dropping them.",
"Walk only on the shadows of objects for ten minutes. Restart if any footstep lands in the light.",
"Manifest your E.G.O suit, kneel, and remove the helmet last while counting aloud every player who passes. Maintain posture until night ends.",
"Parry the first five attacks from every NPC visible to you, then kneel and whisper your Syndicate name silently for one minute per attack.",
"Walk in diagonal steps across Sentenza while clapping silently after each three steps. Reset if interrupted or miscounted.",
"Stand perfectly still at the edge of Hana Outpost for exactly fifteen minutes. Restart if anyone passes too closely or speaks to you.",
"Walk backward through the Backstreets while reciting letters of your rank in reverse. Restart if you step incorrectly or stumble.",
"Sit cross-legged at the center of Death Sentence arena for ten minutes while imagining each attack in slow motion.",
"Manifest your E.G.O suit and remove it piece by piece while spinning clockwise ten times. Do not blink or speak during the process.",
"Follow a random non-Index player for exactly fifty steps. If noticed, kneel immediately and count aloud backwards from ten before resuming.",
"Kneel and recite aloud a monotone sequence of numbers corresponding to the number of NPCs in sight. Pause only if attacked.",
"Walk only along shadows for five minutes. Restart if stepping in the light, stepping outside a shadow, or colliding with a player.",
"Stand on a platform and alternate hopping once per visible player. Maintain position for exactly ten minutes without speaking.",
"Spin clockwise exactly four times at Dead Streets intersection, then walk backward seven paces without looking to your sides.",
"Manifest your E.G.O suit at the tallest building, kneel silently while counting invisible footsteps until night falls.",
"Walk backward toward Hana Outpost while raising your weapon. Lower only when reaching the designated endpoint.",
"Recite a random sequence of numbers for five minutes continuously. Pause only if someone speaks to you, then resume silently.",
"Stand near the platform edge and mimic the posture of the first NPC seen. Hold until they leave or you are attacked.",
"Parry the first three attacks from every fixer visible in Sentenza using your weakest weapon, then drop the weapon and step away silently.",
"Kneel at street center, spinning once per minute while counting aloud in reverse the letters of the first player you saw.",
"Walk diagonally across the Backstreets, shouting 'Observe' each step. Restart if interrupted by a player or object.",
"Manifest your E.G.O suit at night, remove pieces in random order, and remain standing still for exactly ten minutes.",
"Follow a random NPC for fifty steps silently while tracking their movement in reverse mentally. Pause if noticed.",
"Sit cross-legged at the busiest intersection and hum continuously until night falls. Do not move or speak.",
"Kneel near Hana Outpost entrance and silently repeat the first three words of your last Prescript.",
"Walk from Sentenza to Death Sentence arena, counting aloud each shadow you cross. Restart if a shadow is missed.",
"Parry all visible attacks within ten steps for three minutes. Kneel afterward with hands out flat for double the time.",
"Stand at rooftop edge, perform perfect spins without moving feet. Repeat seven times, then step back.",
"Hop through Backstreets for one hundred steps. Pause exactly ten seconds if noticed by another player.",
"Manifest E.G.O suit, remove gloves first, stare silently at all NPCs for five minutes.",
"Follow nearest Index member two paces behind exactly, continue until they leave.",
"Kneel at Sentenza bar, mime drinking invisible cup seven minutes, ignore passersby.",
"Walk backward, spin clockwise at every corner. Reset if stepping out of pattern or colliding.",
"Stand on stairwell, count to seventy-two aloud while performing invisible parries. Repeat if interrupted.",
"Sit in Backstreets center, mime juggling invisible objects for five minutes without dropping.",
"Walk only on shadows for ten minutes. Restart if stepping in light.",
"Manifest E.G.O, kneel, remove helmet last while counting players passing. Maintain posture until night ends.",
"Parry first five attacks from every NPC visible, kneel and whisper Syndicate name silently for one minute per attack.",
"Walk diagonally across Sentenza, clap silently after every three steps. Reset if miscounted or interrupted.",
"Stand still at Hana Outpost edge fifteen minutes. Restart if anyone passes too closely or speaks.",
"Walk backward in Backstreets, recite rank letters in reverse. Restart if stepping incorrectly.",
"Sit cross-legged in Death Sentence arena ten minutes imagining each attack in slow motion.",
"Manifest E.G.O at tallest building, kneel silently counting invisible footsteps until night ends.",
"Walk backward to Hana Outpost raising weapon. Lower only at endpoint.",
"Recite random sequence of numbers five minutes continuously. Pause if someone speaks, then resume silently.",
"DM Darillu 'Happy Birthday' even if it isnt his birthday. If he tells you it isn't his birthday, say 'The Prescript's Will Perseveres' and send him a screenshot of this Prescript. If he says thanks when it isn't his birthday or that you're late/early, then tell him that you will rip his guts out and don't show him a screenshot. If it is actually his birthday, jump off the tallest building in PD, record it and send it to Darillu along with this Prescript.",
"DM Darillu 'Happy Birthday' even if it isnt his birthday. If he tells you it isn't his birthday, say 'The Prescript's Will Perseveres' and send him a screenshot of this Prescript. If he says thanks when it isn't his birthday or that you're late/early, then tell him that you will rip his guts out and don't show him a screenshot. If it is actually his birthday, jump off the tallest building in PD, record it and send it to Darillu along with this Prescript.",
"DM Darillu 'Happy Birthday' even if it isnt his birthday. If he tells you it isn't his birthday, say 'The Prescript's Will Perseveres' and send him a screenshot of this Prescript. If he says thanks when it isn't his birthday or that you're late/early, then tell him that you will rip his guts out and don't show him a screenshot. If it is actually his birthday, jump off the tallest building in PD, record it and send it to Darillu along with this Prescript.",
"DM Darillu 'Happy Birthday' even if it isnt his birthday. If he tells you it isn't his birthday, say 'The Prescript's Will Perseveres' and send him a screenshot of this Prescript. If he says thanks when it isn't his birthday or that you're late/early, then tell him that you will rip his guts out and don't show him a screenshot. If it is actually his birthday, jump off the tallest building in PD, record it and send it to Darillu along with this Prescript.",
"DM Darillu 'Happy Birthday' even if it isnt his birthday. If he tells you it isn't his birthday, say 'The Prescript's Will Perseveres' and send him a screenshot of this Prescript. If he says thanks when it isn't his birthday or that you're late/early, then tell him that you will rip his guts out and don't show him a screenshot. If it is actually his birthday, jump off the tallest building in PD, record it and send it to Darillu along with this Prescript.",
"DM Darillu 'Happy Birthday' even if it isnt his birthday. If he tells you it isn't his birthday, say 'The Prescript's Will Perseveres' and send him a screenshot of this Prescript. If he says thanks when it isn't his birthday or that you're late/early, then tell him that you will rip his guts out and don't show him a screenshot. If it is actually his birthday, jump off the tallest building in PD, record it and send it to Darillu along with this Prescript.",
"DM Darillu 'Happy Birthday' even if it isnt his birthday. If he tells you it isn't his birthday, say 'The Prescript's Will Perseveres' and send him a screenshot of this Prescript. If he says thanks when it isn't his birthday or that you're late/early, then tell him that you will rip his guts out and don't show him a screenshot. If it is actually his birthday, jump off the tallest building in PD, record it and send it to Darillu along with this Prescript.",
}
